
// action name list
export const FETCH_SHIPPMENT_DATA = 'FETCH_SHIPPMENT_DATA';
export const FETCH_SHIPPMENT_DETAIL_DATA = 'FETCH_SHIPPMENT_DETAIL_DATA';
export const UPDATE_SHIPPENT_DATA = 'UPDATE_SHIPPENT_DATA'


